exclude aria-hidden elements
Skyvern-AI/skyvern pull request #557
Opened 2024-07-05 09:20 UTC by LawyZheng

2024-07-05 09:22 UTC, LawyZheng commented on skyvern/webeye/scraper/domUtils.js
> +    return ariaHidden === "false";
except aria-hiden="False" or aria-hiden="false", all aria-hidden values should be considered as hidden, like `aria-hidden`, `aria-hidden=""`, `aria-hidden="true"`, `aria-hidden="True"`

2024-07-06 00:06 UTC, ykeremy requested changes
there is already a isHidden function in this file, we should update it instead.

2024-07-06 00:12 UTC, LawyZheng commented
> there is already a isHidden function in this file, we should update it instead.

we only use the isHidden function for option element, should I enable it to use for all elements ?

2024-07-15 03:11 UTC, closed without merging

2024-07-15 03:11 UTC, LawyZheng commented
Close this PR since it's still controversial to make this change.